### ISSUE TITLE
500ms HTTP request timeout is not honoured

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/cpp-common#132]
We set a 500ms timeout on HTTP connections. However, curl_easy_perform includes a call to curl_multi_wait with a timeout of 1000ms (https://github.com/Metaswitch/curl/blob/master/lib/easy.c#L681), so if the HTTP server is reachable but unresponsive, it will not time out until a multiple of 1000ms have passed.

**Comment by rkd-msw** [comment]
Upstream fix https://github.com/bagder/curl/commit/29bf0598aad58d9da5dd8c5358f5175dae49026d looks like it will address this - we should probably bring curl up to the current master. (@eleanor-merry)

**Comment by eleanor-merry** [comment]
Sadly, this hasn't fixed the issue.

**Comment by eleanor-merry** [comment]
Moving to master does fix the timeouts (but doesn't fix #1090)
