### ISSUE TITLE
Failure to connect to Cassandra has an unhelpful error message

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/cpp-common#186]
The call to `get_client` at https://github.com/Metaswitch/cpp-common/blob/master/src/cassandra_store.cpp#L334 can throw a TTransportException. This is only caught at https://github.com/Metaswitch/cpp-common/blob/master/src/cassandra_store.cpp#L449, which gives the unhelpful log "Unhandled exception when processing cache request'. We should catch TTransportException specifically and give a better log, like we do at https://github.com/Metaswitch/cpp-common/blob/master/src/cassandra_store.cpp#L168.

(Catching NotFoundException and logging sensibly would be good too.)

**Comment by eleanor-merry** [comment]
Fixed by https://github.com/Metaswitch/cpp-common/commit/ae4333dfb0360711badd3132155059ad73342021
