### ISSUE TITLE
100 Continue messages from HTTP stack confuse SAS

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/cpp-common#304]
Our HTTP stack (based on libevhtp) supports sending 100 Continue messages. Curl always adds a `Expect: 100-continue` header`, which means that (for example) if Sprout contacts Homestead the flow is: 

* Request (sprout -> homestead)
* 100 Continue (homestead -> sprout)
* Final response (homestead -> sprout)

Our SAS logging on the client (sprout) sees the 100 Continue but the logging on the server does not. This means the response flows looks different on the two ends, which throws SAS message matching for a loop.

**Comment by bossmc** [comment]
Chronos used to have code to suppress the `100-continue` behaviour in its HTTP client code.

    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers_new);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Expect:') );

The obvious fix (unless there's good reason to want to use `100-continue` processing) is to port this over to the `HTTPConnection` handle initialization code.
