### ISSUE TITLE
SAS call flows are sometimes drawn with out of order events.

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/cpp-common#309]
This issue can occur with just a few calls, but seems to get more pronounced under heavy traffic load (impacting more flows and more events within a flow). Using the time ordering feature can help to clean up a flow, but even with this feature enabled a few messages still may be shown out of order. The latter issue (or possibly both issues) seems to be related to when a message is time-stamped in a reporting NE. As an example, a flow has been captured which by default shows a terminating leg INVITE/Trying interleaved with the originating leg INVITE/Trying reported by a single Sprout. If time ordering is enabled, the flow cleans up a little. But, the Originating Trying is pushed well into the flow because its time-stamp is well after the proxied INVITE for the transaction (and a few subsequent interactions with the TAS). It seems like since the Trying is turned around immediately upon receiving the INVITE, its time-stamp should have preceded the proxied INVITE generated by Sprout. A similar behavior can be seen with the 200 OK proxied by Sprout. The time-stamp for the proxied 200 OK is earlier than the received 200 OK.

**Comment by mirw** [comment]
OK, so in both the working and non-working cases, the flow is

*   INVITE from UE to P-CSCF, and 100 Trying back
*   INVITE from P-CSCF to Sprout, and 100 Trying back
*   INVITE from Sprout to originating TAS, and 100 Trying back
*   INVITE from originating TAS to Sprout, and 100 Trying back
*   INVITE from Sprout to terminating TAS, and 100 Trying back
*   INVITE from terminating TAS to Sprout, and 100 Trying back
*   INVITE from Sprout to P-CSCF, and 100 Trying back
*   INVITE from P-CSCF to other UE, and 100 Trying back.

The difference between the two flows appears to be when the P-CSCF receives the 100 Trying from Sprout.

*   In the working case, it receives it before the INVITE back from Sprout.
*   In the non-working case, it receives it after the INVITE back from Sprout.

Sprout always logs that it has sent the 100 Trying to P-CSCF first.  Maybe the 100 Trying is being delayed in transit (or in Sprout or the P-CSCF's networking stack)?

@plfrancis, please can you take a look at

*   why this message is being traced by the P-CSCF out of order
    *   maybe it's due to the level of stress we're running
    *   maybe it's due to the presence of the TAS
*   whether this is actually a Sprout bug - it doesn't appear that Sprout could do anything better?

**Comment by plfrancis** [comment]
I've tried to reproduce this issue at very low call traffic (10 originators to 10 terminators, 3 CPS for 3+ seconds, 20 second hold, 10 second inter-call, for 2 cycles => 20 total calls). Out of 20 calls, 3 showed a possible precursor to the out of order message issue. SAS seems to be unable to correlate a message between Sprout and Perimeta that are in order and have minimal time between send/receive. I've uploaded 3 such flows. Two show this issue with 200 OK to INVITE, and one shows it with 200 OK to BYE. The SAS seems to be indicating that the messages from the two sides are either reporting different content than what was sent/received, or the messages were out of order. In this case it seems to point to the former. I grabbed a wireshark trace from Sprout and Perimeta and tried to use the VPED decoder to determine if this was true or not, but the message data seems to be in binary format. There is probably a way to dump this from the SAS trace itself, but I do not know how to do that. Passing back for analysis.

I will try the same scenario with the latest load that has SAS compression disabled and see if the problem still exists.

**Comment by mirw** [comment]
The reason that SAS sees these as out-of-order is that between Sprout sending the 200 OK and Perimeta receiving the 200 OK, Sprout also sends an HTTP POST to Ralf and receives the response.  (You can see this by enabling experimental features and then choosing "Show HTTP".)

I don't know whether SAS could do better at correlating these, in particular when HTTP flows are hidden, but this is why it's behaving the way it is.

**Comment by mirw** [comment]
@plfrancis, as above, I don't think there's anything Clearwater can do differently here (apart from maybe not log HTTP flows), and I don't think SAS compression will change anything.  Passing back to you to decide how to handle.

**Comment by plfrancis** [comment]
This issue is now being tracked with the SAS team via SFR 478147. Closing.
