### ISSUE TITLE
Portions of BYE transactions split into multiple SAS traces.

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/cpp-common#310]
When isolating a Sprout node from the network, the VoLTE TAS causes some calls to fail since it does not apparently handle the error case well. The result is that it does not respond at all to BYE messages until it detects the link failure to Sprout. Looking at a SAS trace for these failed calls it was seen that the failed BYE transactions were being split out into multiple call flows. It was necessary to search by Call-ID to locate the missing parts. An example of the three flows has been uploaded.

**Comment by mirw** [comment]
The issue here is that the BYE occurs more than 1 minute after the initial INVITE.  SAS only correlates markers on trails within the first minute.

I don't think there's anything else we can do from a Clearwater perspective.

**Comment by mirw** [comment]
@plfrancis, passing back to you to consider/close.

**Comment by plfrancis** [comment]
A fix is being worked by the SAS team for their 9.2 release. Closing.
