### ISSUE TITLE
POSTs and PUTs from HttpConnection have wrong Content-Type

### ISSUE THREAD

**Issue by dimbleby** [Metaswitch/cpp-common#336]
Requests have `application/x-www-form-urlencoded`, where `application/json` is intended.

Looks like the problem is that although `HttpConnection::send_put()` and `send_post()` both set `CURLOPT_HTTPHEADER` with `Content-Type: application/json`, when we get to `send_request()` that sets the option again without this header.

I have a fix that works for me - let me know how you'd like me to go about submitting it to you.

**Comment by bossmc** [comment]
Fixed by https://github.com/Metaswitch/cpp-common/pull/338.
