### ISSUE TITLE
SAS can't decode all Diameter messages

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/cpp-common#373]
`Error while decoding Diameter message: Header message length and data length differ (Header length: 1040 bytes; data length: 1037 bytes)`

I don't see it on all Diameter messages - approximately half. The discrepancy seems to always be 2 or 3 bytes. Seen on both the Rf and Cx interfaces.

Should be easy to repo on the VMWare system.

**Comment by graemerobertson** [comment]
Raising to high priority because this issue may be causing correlation issues, and is blocking other work.

**Comment by graemerobertson** [comment]
False alarm, lowering again. Never even removed the medium-priority tag so basically nailed it.

**Comment by graemerobertson** [comment]
Diameter messages are padded to 4-byte multiples (with 0 bytes) on the wire (and the header reflects this).  It looks like when we hook into freeDiameter's message send, the message has not yet had padding applied so we end up sending the message to SAS without padding but with a header that expects it.  We should either add padding ourselves before we send the message to SAS or enhance the SAS diameter to handle unpadded messages.

**Comment by bossmc** [comment]
More investigation revealed that we were sending the correct data, but SAS was getting confused and was treating the data as a UTF-8 string(somtimes) leading to it miscounting the "length" of the string (since it was treating two bytes as one character).

The SAS issue will be fixed with the v9.2 release of SAS.
