### ISSUE TITLE
If opening a log file fails, we might not retry for a long time

### ISSUE THREAD

**Issue by mirw** [Metaswitch/cpp-common#383]
I was messing around with my system, and my Homestead process failed to cycle its log file.  It then proceeded not to log again for over an hour (even after I'd fixed the problem), when it restarted logging with:

```
23-09-2015 11:24:01.056 UTC Failed to open logfile (13 - Permission denied), 2000 logs discarded23-09-2015 11:24:01.056 UTC Status freeDiameter: [dbg_monitor] Dumping queues statistics
23-09-2015 11:24:01.083 UTC Status freeDiameter: Global 'Local delivery': cur:0/25, h:0, T:0 in 0.000000s (-NANitems/s), blocked:0.000000s, last processing:0.000000s
23-09-2015 11:24:01.083 UTC Status freeDiameter: Global 'Total received': cur:0/20, h:0, T:0 in 0.000000s (-NANitems/s), blocked:0.000000s, last processing:0.000000s
23-09-2015 11:24:01.083 UTC Status freeDiameter: Global 'Total sending': cur:0/30, h:0, T:0 in 0.000000s (-NANitems/s), blocked:0.000000s, last processing:0.000000s
```

I think the issue here is that we only try to reopen log files once every 1000 logs - if logging is low, this could be a long time.  I think we should switch to trying to reopen every time a log comes in that is more than say 5s after the last attempt.

**Comment by chris-elford-metaswitch** [comment]
#452 covers the fix for this issue. I've live tested and all the UTs pass so I'm going to close.
