### ISSUE TITLE
Load Monitor keeps increasing token rate even if current rate is unproven

### ISSUE THREAD

**Issue by mirw** [Metaswitch/cpp-common#384]
Watching my (broadly idle) Sprout node, I see the token rate constantly increasing.  This means that, if I were to have a sudden spike in traffic, I would give poor behavior to a larger number of requests, while it took time for me to adjust my load back down to the correct number

The logic behind increasing the token rate is that the current latency is within bounds (and we haven't had any penalties rejected from upstream).  This is basically the algorithm given in the [Adaptive Overload Control for Busy Internet Servers](http://www.eecs.harvard.edu/~mdw/papers/control-usits03.pdf) paper.  Instead, I think we should only increase the rate if we're using some (large-ish) fraction of the current token rate - if we're not, there's no evidence that we can actually support an increased number of requests.

@eleanor-merry suggests this might be related to https://github.com/Metaswitch/sprout/issues/1090 - it's not clear, but worth bearing in mind.

**Comment by mike-evans** [comment]
Sounds like a sensible solution.  I had a brief worry about start-up behaviour (ie. whether we would stabilise on a high enough token rate), but I think this should work fine.
