### ISSUE TITLE
Cpp processes no longer do anything on a sighup/sigusr1

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/cpp-common#504]
#### Symptoms
Running 'service <service> reload' should trigger the service to reload its configuration (e.g. cluster settings). Instead, it silently fails.

#### Impact
Elastic scaling doesn't work, re-synchronising data after a crash doesn't work

#### Release and environment 
This works in the Articuno release, and doesn't in the Charizard release

**Comment by mirw** [comment]
If this is also in release-94-fixes, I think we need to mark it critical.

**Comment by eleanor-merry** [comment]
It's not :hamster:

**Comment by eleanor-merry** [comment]
This was broken by the move to have all processes self-daemonize (e.g. https://github.com/Metaswitch/sprout/pull/1374/files, https://github.com/Metaswitch/cpp-common/pull/491/files)

**Comment by eleanor-merry** [comment]
This is another issue where we create some threads before we fork the process. The signal handler threads get created right at the start, and are then lost when we daemonise ourselves. This also explains why some of the cpp processes have started crashing on shut down. 

Fix is to move the thread initialisation out of the signal handler constructor
