### ISSUE TITLE
SNMP scalars are exposed under the wrong OID

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/cpp-common#523]
Clearwater exposes most of its statistics as tables, but some as scalars (single values). In SNMP scalars are exposed in a slightly weird way. Take for example the `sproutPRRCurrentValue` defined in [PROJECT-CLEARWATER-MIB](https://github.com/Metaswitch/clearwater-snmp-handlers/blob/3d0e4761ec7b9cf1d87c77663090976021800544/PROJECT-CLEARWATER-MIB#L2406). It looks like it should be exposed at the OID `1.2.826.0.1.1578918.9.3.31`. However it should actually be exposed at `1.2.826.0.1.1578918.9.3.31.0` (note the trailing `.0`).

I believe this only affects the following sprout stats, but I regard it as a bug in our stats infrastructure so raising it here:

* sprout_smoothed_latency
* sprout_target_latency
* sprout_penalties
* sprout_current_token_rate

**Comment by AlexHockey** [comment]
@nicolemcp I'm planning on fixing this imminently. This is technically an API change (since the stats will be exposed under a new OID and not at the old OID) so please shout ASAP if you think this is going to cause a problem.

**Comment by steelyvoid** [comment]
Adding myself as participant so that I can be notified on closure
